/**
 * Keyword to font family mapping
 *
 * Auto-generated from agentic font matching results.
 * DO NOT EDIT MANUALLY - regenerate with prepare-keyword-fonts.ts
 */

export const KEYWORD_FONTS: Record<string, string> = {
  "curtains": "Dancing Script",
  "spider web": "Eater",
  "inspiration": "Monoton",
  "tourists": "Mountains of Christmas",
  "movement": "Qwitcher Grypen",
  "possibility": "Eater",
  "contrasts": "Bungee",
  "expectation": "Merriweather",
  "fear": "Creepster",
  "compassion": "Fira Sans",
  "entitlement": "Parisienne",
  "facades": "Dancing Script",
  "machine": "Orbitron",
  "distrust": "Syne Mono",
  "image": "Great Vibes",
  "patchwork": "Eater",
  "illusion": "Creepster",
  "oneness": "Open Sans",
  "impulses": "Oregano",
  "hand": "Kalam",
  "benefit": "Merriweather",
  "conformity": "Oswald",
  "maze": "Architects Daughter",
  "high": "Dancing Script",
  "completion": "Merriweather",
  "discovery": "Syne Mono",
  "shapeshifting": "Rubik Glitch",
  "Absolute": "Ubuntu",
  "stories": "Great Vibes",
  "otherness": "Creepster",
  "ambition": "Merriweather",
  "smile": "Indie Flower",
  "satisfaction": "Merriweather",
  "attractor": "Eater",
  "psychedelics": "Cabin Sketch",
  "exploration": "Permanent Marker",
  "momentum": "Knewave",
  "indifference": "Rubik",
  "structure": "Teko",
  "belief": "Merriweather",
  "misogyny": "Creepster",
  "appearance": "Italianno",
  "subscription": "Merriweather",
  "potential": "Bungee Spice",
  "public": "Fira Sans",
  "feedback": "Merriweather",
  "projection": "Syne Mono",
  "social context": "Playfair Display",
  "joy": "Indie Flower",
  "destruction": "Creepster",
  "sense-making": "Readex Pro",
  "identification": "Roboto",
  "regularity": "Roboto",
  "embodiment": "Fira Sans",
  "breathe": "Open Sans",
  "familiarity": "Playfair Display",
  "gender": "Merriweather Sans",
  "autistic": "Creepster",
  "bliss": "Indie Flower",
  "experience": "Merriweather",
  "finding": "Monoton",
  "history": "Libre Baskerville",
  "types": "DM Sans",
  "connection": "Monoton",
  "intuition": "Archivo",
  "doodling": "Indie Flower",
  "demonstration": "Roboto",
  "grammatical": "Oswald",
  "alcohol": "Dancing Script",
  "constraint": "Ubuntu",
  "interaction": "Caveat",
  "belonging": "Playfair Display",
  "verification": "Roboto",
  "sensation": "Modak",
  "reality": "Gravitas One",
  "persuasion": "Merriweather",
  "unity": "Gravitas One",
  "prey": "Caveat",
  "meditation": "Fira Sans",
  "appreciation": "Dancing Script",
  "overload": "Modak",
  "togetherness": "Open Sans",
  "human nature": "Fira Sans",
  "individuation": "Monoton",
  "mathematics": "Readex Pro",
  "character": "Dancing Script",
  "luck": "Mountains of Christmas",
  "rationalization": "Roboto",
  "semantics": "Readex Pro",
  "resonance": "Dancing Script",
  "mechanism": "Electrolize",
  "commitment": "Merriweather",
  "middle": "Fira Sans",
  "lucidity": "Readex Pro",
  "insight": "Bungee Shade",
  "cognition": "Roboto",
  "gravity": "Ubuntu",
  "landscape": "Hammersmith One",
  "learning": "Edu SA Beginner",
  "delusion": "Creepster",
  "statement": "Limelight",
  "moment": "Fira Sans",
  "universality": "Fira Sans",
  "cancer": "Gravitas One",
  "mental activity": "Monoton",
  "environment": "Fira Sans",
  "urge": "Caveat",
  "wave": "Wavefont",
  "utterance": "Caveat",
  "it": "Inter",
  "recognition": "Playfair Display",
  "leading questions": "Italianno",
  "value": "Merriweather",
  "protection": "Roboto",
  "self-defeat": "Creepster",
  "political subject": "Archivo",
  "claims": "PT Serif",
  "disappearance": "Redacted",
  "voice": "Pacifico",
  "new": "Outfit",
  "inclusion": "Inclusive Sans",
  "agency": "Oswald",
  "power structures": "Archivo Black",
  "reference": "IBM Plex Serif",
  "prediction": "Space Grotesk",
  "return": "Nunito",
  "order": "Roboto Condensed",
  "curiosity": "Great Vibes",
  "structures": "IBM Plex Sans",
  "creation": "Dancing Script",
  "arrived": "Alfa Slab One",
  "signature": "Great Vibes",
  "awareness": "Lora",
  "moves": "Permanent Marker",
  "here": "Inter",
  "introduction": "Lato",
  "inconsistency": "Caveat Brush",
  "physicality": "Anton",
  "collaboration": "Work Sans",
  "resistance": "Black Han Sans",
  "AI": "Orbitron",
  "feeling": "Satisfy",
  "walls": "Bebas Neue",
  "adaptation": "Rajdhani",
  "visual feedback": "Noto Color Emoji",
  "enjoyment": "Bubblegum Sans",
  "skill": "IBM Plex Mono",
  "rock": "Bebas Neue",
  "moments": "Montserrat",
  "words": "Open Sans",
  "mental states": "Shadows Into Light",
  "neutrality": "Roboto Mono",
  "walking": "Kalam",
  "meaning": "EB Garamond",
  "pairs": "Poppins",
  "jiu-jitsu": "Racing Sans One",
  "social roles": "Roboto",
  "simultaneity": "Inter",
  "comfort": "Nunito",
  "fragments": "Special Elite",
  "climb": "Caveat",
  "participation": "Poppins",
  "care": "Dancing Script",
  "disruption": "Bungee Spice",
  "abundance": "Playfair Display",
  "readiness": "Roboto Condensed",
  "reflection": "Lora",
  "visibility": "Anton",
  "human abilities": "Ubuntu",
  "relaxation": "Caveat Brush",
  "solutions": "Outfit",
  "plans": "Work Sans",
  "dissonance": "Eater",
  "explanation": "Lexend",
  "programming": "JetBrains Mono",
  "avoidance": "Manrope",
  "emotion": "Pacifico",
  "violence": "Alfa Slab One",
  "technology": "Space Grotesk",
  "continuity": "Raleway",
  "suitability": "Figtree",
  "ability": "Barlow",
  "coherence": "IBM Plex Sans",
  "propaganda": "Bebas Neue",
  "symbol": "Noto Emoji",
  "shapelessness": "Varela Round",
  "autonomy": "Inconsolata",
  "gratitude": "Great Vibes",
  "beauty": "Cormorant Garamond",
  "system": "DM Sans",
  "naming": "Lato",
  "individuality": "Josefin Sans",
  "frequency": "Roboto Mono",
  "creativity": "Fredoka",
  "guesses": "Indie Flower",
  "encounter": "Kalam",
  "differences": "Archivo",
  "domination": "Anton",
  "transgender": "Rubik",
  "force": "Gravitas One",
  "assumptions": "Caveat",
  "binary choice": "Questrial",
  "sneezing": "Chewy",
  "social change": "Protest Revolution",
  "defenses": "Barlow Condensed",
  "communication": "Open Sans",
  "miracle": "Great Vibes",
  "narrative": "Merriweather",
  "body": "Roboto",
  "mental space": "Inter",
  "distance": "Roboto Condensed",
  "self-awareness": "Raleway",
  "failure": "Creepster",
  "color": "Noto Color Emoji",
  "collective": "Nunito Sans",
  "pattern": "Raleway",
  "interpretation": "Lora",
  "presence": "Playfair Display",
  "individual": "Work Sans",
  "limits": "Oswald",
  "risk": "Anton",
  "threshold": "Italiana",
  "magic": "Allura",
  "cults": "Grenze Gotisch",
  "chimps": "Fredericka the Great",
  "outer": "Orbitron",
  "dating": "Dancing Script",
  "person": "Poppins",
  "speech": "Caveat",
  "kindness": "Comfortaa",
  "cycle": "Raleway",
  "instability": "Pangolin",
  "difficulty": "Roboto Slab",
  "worlds": "Prata",
  "height": "Bebas Neue",
  "metaphor": "EB Garamond",
  "categories": "Archivo",
  "routine": "IBM Plex Sans",
  "present moment": "Quicksand",
  "rhythm": "Ubuntu",
  "dominance": "Gravitas One",
  "intelligence": "Spectral",
  "party": "Pacifico",
  "analysis": "PT Sans",
  "letting go": "Satisfy",
  "hiding": "Redacted",
  "life": "Montserrat",
  "self-deception": "Abril Fatface",
  "significance": "Cinzel",
  "wholeness": "Barlow",
  "self": "Lato",
  "social positions": "Titillium Web",
  "questions": "Inconsolata",
  "space": "Space Mono",
  "world": "Roboto",
  "ultimate question": "Inter",
  "softness": "Nunito",
  "nature": "Alegreya",
  "writing": "Caveat",
  "static mind": "IBM Plex Mono",
  "community": "Nunito Sans",
  "purification": "Raleway",
  "need": "Oswald",
  "shape": "Montserrat",
  "window": "Open Sans",
  "unfinished": "Caveat Brush",
  "sadness": "Lora",
  "diversity": "Noto Sans",
  "justice": "Playfair Display",
  "opportunity": "Figtree",
  "life architecture": "Roboto Slab",
  "ambiguity": "Work Sans",
  "healing": "Poppins",
  "light": "Raleway",
  "BJJ": "Bebas Neue",
  "self-perception": "Dancing Script",
  "QRI": "Space Grotesk",
  "comparison": "Inter",
  "perception": "Lato",
  "phone calls": "Source Code Pro",
  "deflection": "Skranji",
  "dreams": "Great Vibes",
  "activation": "Passion One",
  "merging": "Quicksand",
  "silence": "Inconsolata",
  "possibilities": "Outfit",
  "science": "Inconsolata",
  "language": "PT Serif",
  "dance": "Pacifico",
  "engagement": "Poppins",
  "confidence": "Anton",
  "self-discovery": "Indie Flower",
  "installation": "Allerta Stencil",
  "now": "IBM Plex Sans",
  "subjectivity": "Caveat",
  "touch": "Patrick Hand",
  "solitude": "Crimson Text",
  "anxiety": "Creepster",
  "answers": "Source Sans 3",
  "human": "Lato",
  "quorum sensing": "Chakra Petch",
  "coping": "Nunito",
  "focus": "IBM Plex Mono",
  "measurement": "Roboto Mono",
  "decisions": "Roboto",
  "success": "Gravitas One",
  "windows": "Inter",
  "intention": "DM Sans",
  "pleasure": "Pacifico",
  "biology": "Noto Sans",
  "thoughts": "Caveat",
  "video calls": "Roboto",
  "complexity": "IBM Plex Mono",
  "isolation": "Inconsolata",
  "difference": "Archivo",
  "music": "Monoton",
  "state": "Open Sans",
  "stimulants": "Anton",
  "group norms": "Raleway",
  "phenomenology": "Merriweather",
  "integrity": "Roboto Slab",
  "observation": "Lora",
  "identity": "Ubuntu",
  "challenges": "Oswald",
  "hypothesis": "IBM Plex Sans",
  "love": "Great Vibes",
  "meetup": "Nunito Sans",
  "boundary": "Space Mono",
  "utility": "Figtree",
  "constraints": "Barlow Condensed",
  "inner conflict": "Indie Flower",
  "clear": "Lexend",
  "frustration": "Creepster",
  "leadership": "Playfair Display",
  "disorientation": "VT323",
  "sleep": "Shadows Into Light",
  "empathy": "Kalam",
  "vinyl": "Rubik Dirt",
  "ephemeral": "Pacifico",
  "preference": "Quicksand",
  "conversation": "Nunito",
  "oppression": "Anton",
  "point": "Space Grotesk",
  "transition": "Roboto",
  "tablet": "Inter",
  "dimension": "Abril Fatface",
  "time": "Roboto Mono",
  "flying": "Audiowide",
  "incompatibility": "Creepster",
  "power": "Bebas Neue",
  "discussion": "Open Sans",
  "disability": "Atkinson Hyperlegible Next",
  "conditions": "Roboto",
  "sound": "Space Mono",
  "social": "Open Sans",
  "release": "Oswald",
  "dialogue": "Inter",
  "audience": "Lato",
  "support": "Nunito",
  "civil rights": "Anton",
  "coffee": "Bitter",
  "uncertainty": "Caveat",
  "demotivation": "Creepster",
  "psyche": "Spectral",
  "existence": "EB Garamond",
  "change": "Manrope",
  "inner": "Shadows Into Light",
  "bacteria": "IBM Plex Mono",
  "motivation": "Playfair Display",
  "ChatGPT": "Space Grotesk",
  "arrival": "Rubik",
  "peace": "Raleway",
  "warmth": "Merriweather",
  "reader": "Lexend",
  "choice": "DM Sans",
  "adaptability": "Roboto Flex",
  "paradox": "Monoton",
  "vulnerability": "Indie Flower",
  "stage": "Abril Fatface",
  "drugs": "Special Elite",
  "attention": "Gravitas One",
  "self-reference": "Dancing Script",
  "thinking": "Merriweather",
  "childhood": "Shadows Into Light Two",
  "forms": "Raleway",
  "drumming": "Monoton",
  "independence": "Archivo Black",
  "neurotypical": "Roboto",
  "transformation": "Teko",
  "view": "Noto Sans",
  "self-acceptance": "Comfortaa",
  "we": "Nunito Sans",
  "pressure": "Anton",
  "confusion": "Caveat Brush",
  "self-definition": "Prata",
  "guidance": "PT Sans",
  "homeless": "Creepster",
  "culture": "Lora",
  "role": "Outfit",
  "contradiction": "Alegreya",
  "divine": "Cormorant Garamond",
  "forget": "Shadows Into Light",
  "religion": "Cinzel",
  "justification": "Roboto",
  "personal": "Caveat",
  "expression": "Dancing Script",
  "activities": "Nunito Sans",
  "conversation partner": "Open Sans",
  "babies": "Comfortaa",
  "necessity": "Oswald",
  "devices": "Space Mono",
  "madness": "Creepster",
  "universals": "Noto Sans",
  "mad-labeling": "Monoton",
  "whiteness": "Raleway",
  "habituation": "Lato",
  "unrealized": "Pacifico",
  "improvement": "Montserrat",
  "practice": "Patrick Hand",
  "energy": "Anton",
  "traps": "Eater",
  "freedom": "Fredoka",
  "interface": "Inter",
  "unknown": "VT323",
  "compression": "Roboto Condensed",
  "emotional intelligence": "Poppins",
  "puzzles": "Quicksand",
  "shared space": "Raleway",
  "doubt": "Indie Flower",
  "control": "IBM Plex Sans",
  "being": "EB Garamond",
  "categorization": "Archivo",
  "dogs": "Bangers",
  "truth": "Noto Serif",
  "objective": "DM Sans",
  "occupation": "Roboto",
  "chemical language": "IBM Plex Mono",
  "farewell": "Great Vibes",
  "scale": "Oswald",
  "progress": "Outfit",
  "stability": "Merriweather",
  "instructions": "Lexend",
  "cooperation": "Poppins",
  "knowledge": "PT Serif",
  "app": "Roboto",
  "friction": "Special Elite",
  "muscles": "Alfa Slab One",
  "judgment": "Bitter",
  "chaos": "Nosifer",
  "trust": "Merriweather",
  "mind": "Orbitron",
  "pain": "Creepster",
  "surprise": "Eater",
  "listening": "Open Sans",
  "flexibility": "Roboto Flex",
  "conflict": "Barlow",
  "essential": "Lexend",
  "desire": "Great Vibes",
  "uniqueness": "Fredericka the Great",
  "neural network": "IBM Plex Mono",
  "refinement": "EB Garamond",
  "hybridization": "Rubik",
  "boundaries": "Fjalla One",
  "spectrum": "Raleway",
  "contact": "Poppins",
  "Hegel": "EB Garamond",
  "stretch": "Oswald",
  "excuse": "Caveat",
  "conceptual worlds": "Montserrat",
  "context": "Inter",
  "orientation": "Ubuntu",
  "shared experience": "Nunito",
  "humility": "Roboto",
  "placeholder": "Inconsolata",
  "understanding": "Merriweather",
  "medium": "Lato",
  "display": "Playfair Display",
  "thinkers": "Crimson Text",
  "mad studies": "Indie Flower",
  "money": "Courier Prime",
  "openness": "Open Sans",
  "acceptance": "Nunito Sans",
  "fiction": "Lora",
  "word2vec": "Space Mono",
  "causation": "PT Serif",
  "places": "Noto Serif",
  "analogy": "Spectral",
  "play": "Pacifico",
  "autism": "Atkinson Hyperlegible Next",
  "subjective": "Caveat",
  "reading": "Merriweather",
  "safety": "Roboto",
  "cult": "Grenze Gotisch",
  "performance": "Alfa Slab One",
  "concepts": "Montserrat",
  "God": "Frank Ruhl Libre",
  "survival": "Bebas Neue",
  "tradition": "Cormorant Garamond",
  "collective action": "Space Grotesk",
  "passivity": "Raleway",
  "group": "Nunito Sans",
  "threads": "Inconsolata",
  "home": "Poppins",
  "betweens": "Work Sans",
  "fixed idea": "Roboto Condensed",
  "plant": "Caveat",
  "coordination": "Inter",
  "technique": "IBM Plex Sans",
  "atoms": "Gravitas One",
  "reason": "Lora",
  "detail": "EB Garamond",
  "politeness": "Open Sans",
  "abstraction": "Montserrat",
  "markers": "Permanent Marker",
  "loss": "Merriweather",
  "ape": "Bangers",
  "persistence": "Oswald",
  "trace": "Patrick Hand",
  "inside": "Alegreya",
  "comedy": "Pacifico",
  "emotions": "Dancing Script",
  "misunderstanding": "Creepster",
  "unrelatable": "Space Mono",
  "novelty": "Press Start 2P",
  "perspective": "Raleway",
  "efficiency": "Roboto",
  "thought": "Playfair Display",
  "attitude": "Archivo Black",
  "certainty": "Anton",
  "relationships": "Noto Sans",
  "weird": "Eater",
  "criticism": "Barlow",
  "anticipation": "Caveat Brush",
  "consciousness": "Noto Serif",
  "humanity": "Fira Sans",
  "habit": "Outfit",
  "evidence": "IBM Plex Mono",
  "sense": "Lato",
  "recipe": "Indie Flower",
  "simplicity": "Lexend",
  "tension": "Manrope",
  "rationality": "DM Sans",
  "intensity": "Bebas Neue",
  "memory": "Crimson Text",
  "imagination": "Great Vibes",
  "indecision": "Sofia",
  "separation": "Space Grotesk",
  "ideas": "Quicksand",
  "inclusivity": "Atkinson Hyperlegible Next",
  "seriousness": "Roboto Slab",
  "rest": "Raleway",
  "authenticity": "Merriweather",
  "error": "Roboto Mono",
  "waiting": "Lora",
  "extremes": "Anton",
  "growth": "Poppins",
  "research": "IBM Plex Sans",
  "conviction": "Playfair Display",
  "self-expression": "Pacifico",
  "sensory": "Great Vibes",
  "hybrids": "Playfair Display",
  "differentiation": "Space Grotesk",
  "Brazilian jiu-jitsu": "Roboto Condensed",
  "future": "Orbitron",
  "action": "Rubik",
  "door": "Oswald",
  "forgetting": "Redacted",
  "hamsters": "Comic Neue",
  "clarity": "Inter",
  "fame": "Lobster",
  "active discovery": "Caveat",
  "active exploration": "Caveat Brush",
  "adaptability and prediction": "Roboto Flex",
  "adaptability prediction discovery": "Roboto Flex",
  "adaptation conformity": "Montserrat",
  "adaptive capacity": "Raleway",
  "adaptive conformity": "Open Sans",
  "adaptive coping": "Nunito",
  "adaptive discovery": "Indie Flower",
  "adaptive movement": "Exo 2",
  "adaptive prediction": "Space Grotesk",
  "adaptive protection": "Rubik",
  "adaptive protection strategies": "IBM Plex Sans",
  "adaptive survival": "Bitter",
  "aesthetic appreciation": "Cormorant Garamond",
  "aesthetic experience": "Italianno",
  "aesthetic value": "EB Garamond",
  "altered consciousness": "VT323",
  "altered consciousness states": "Monoton",
  "analytical frameworks": "Source Sans 3",
  "analytical observation frameworks": "IBM Plex Sans",
  "analytical perspective": "Domine",
  "analytical perspective observation": "Spectral",
  "animal behavior": "Caveat",
  "animal cognition": "Nunito",
  "animal companions": "Quicksand",
  "answers and animals": "Patrick Hand",
  "answers and companions": "Baloo 2",
  "answers and intuition": "Sacramento",
  "answers animals": "Noto Sans",
  "answers guidance": "Open Sans",
  "anxiety and fear": "Merriweather",
  "anxiety and worry": "Lora",
  "anxiety disorders": "Inter",
  "anxiety experience": "Merriweather",
  "anxiety states": "Roboto",
  "anxiety stress": "IBM Plex Sans",
  "anxiety worry": "PT Sans",
  "appearance and form": "Playfair Display",
  "artificial intelligence": "Space Grotesk",
  "attention and presence": "Figtree",
  "attentive presence": "DM Sans",
  "attentive resonance": "EB Garamond",
  "authentic self": "Caveat",
  "authentic self awareness": "Indie Flower",
  "authentic self-awareness": "Shadows Into Light",
  "authentic selfhood": "Pacifico",
  "authenticity and being": "Great Vibes",
  "basic resources": "Roboto",
  "basic survival": "Arimo",
  "belief and communication": "Lato",
  "belief and expression": "Raleway",
  "belief expression": "Outfit",
  "belief expression communication": "Nunito Sans",
  "biological agents": "Inter",
  "biological elements": "Noto Sans",
  "biological imperative": "IBM Plex Sans",
  "biological substances": "Roboto Mono",
  "bodily existence": "Merriweather",
  "bodily experience": "Lora",
  "bodily experience safety": "Nunito",
  "bodily self": "Caveat",
  "causal reasoning": "IBM Plex Sans",
  "causality and ethics": "Lora",
  "causality and justice": "Playfair Display",
  "causality reason": "Roboto",
  "causation and justice": "EB Garamond",
  "causation and meaning": "Merriweather",
  "causation and morality": "Noto Serif",
  "causation reason justification": "Inter",
  "challenge and conviction": "Roboto Slab",
  "challenge and doubt": "Lora",
  "change and growth": "Poppins",
  "change and surprise": "Pacifico",
  "change and transformation": "Raleway",
  "change transformation": "Montserrat",
  "change transformation surprise": "Quicksand",
  "character and practice": "Merriweather",
  "character development practice": "Lato",
  "character meditation practice": "Roboto",
  "choice and decision": "Inter",
  "choice decision": "Open Sans",
  "cognition intelligence coherence": "IBM Plex Sans",
  "cognitive analysis": "Roboto Mono",
  "cognitive feedback": "Rubik",
  "cognitive function": "Source Sans 3",
  "cognitive intelligence": "Outfit",
  "cognitive intelligence coherence": "Space Grotesk",
  "cognitive interpretation": "Lora",
  "cognitive mapping": "Figtree",
  "cognitive processing": "DM Sans",
  "cognitive understanding": "Noto Sans",
  "collaborative action": "Nunito Sans",
  "collaborative intention": "Poppins",
  "collaborative learning": "Raleway",
  "collaborative learning boundaries": "Barlow",
  "collaborative learning growth": "Fredoka",
  "collective creation": "Work Sans",
  "collective creation intention": "Montserrat",
  "collective creation skill": "Jost",
  "collective intention": "Mulish",
  "collective intention creation": "Plus Jakarta Sans",
  "collective learning": "Comfortaa",
  "collective learning boundaries": "Archivo",
  "collective skill building": "Manrope",
  "collective transformation": "Urbanist",
  "commitment and integrity": "Merriweather",
  "communication and expression": "Open Sans",
  "communication belief": "Playfair Display",
  "communication expression": "Dancing Script",
  "community and madness": "Pacifico",
  "community shared experience": "Indie Flower",
  "completion and necessity": "Roboto Slab",
  "completion necessity": "Arvo",
  "conditional incompatibility": "Oswald",
  "conditions compatibility": "Quicksand",
  "conditions incompatibility": "Bebas Neue",
  "conflict and dominance": "Gravitas One",
  "conflict and group dynamics": "Anton",
  "conflict and harm": "Creepster",
  "conflict and violence": "Nosifer",
  "conflict group dynamics": "Chango",
  "conflict violence": "Rammetto One",
  "conformity adaptation": "Nunito",
  "conformity and protection": "Ubuntu",
  "conformity protection": "Raleway",
  "consciousness and commitment": "Cinzel",
  "constraints optimization": "Exo 2",
  "contemplative practice": "Satisfy",
  "contextual analysis": "Inter",
  "contradiction and diversity": "Roboto",
  "coping and illusion": "Playfair Display",
  "coping and symbolism": "Dancing Script",
  "coping mechanisms": "Merriweather",
  "coping mechanisms symbolism": "Great Vibes",
  "coping rationalization meaning": "Lora",
  "creative expression": "Caveat",
  "critical challenges": "Oswald",
  "critical doubt": "IBM Plex Sans",
  "critical self-examination": "Open Sans",
  "curiosity and challenge": "Space Grotesk",
  "curiosity and criticism": "Work Sans",
  "curiosity and self-doubt": "Rubik",
  "curiosity self-doubt conviction": "Plus Jakarta Sans",
  "daily living practices": "Nunito",
  "daily practice": "Poppins",
  "daily practice habits": "Quicksand",
  "daily practice rituals": "Raleway",
  "daily practices": "Lato",
  "daily practices habits": "Jost",
  "daily resources": "Archivo",
  "daily support": "Comfortaa",
  "daily sustenance": "Ubuntu",
  "daily sustenance success": "Source Sans 3",
  "decision making": "Barlow",
  "decision-making": "Titillium Web",
  "defensive adaptation": "Archivo Narrow",
  "defensive meaning-making": "PT Sans",
  "destructive conflict": "Anton",
  "devices and display": "IBM Plex Mono",
  "dialogic encounter": "Fira Sans",
  "dialogical encounter": "Lexend",
  "dialogue and disruption": "Bungee Spice",
  "dialogue and mystery": "EB Garamond",
  "dialogue and unknown": "Caveat Brush",
  "dialogue conversation unknown": "Kalam",
  "dialogue unknown": "Gloria Hallelujah",
  "difference and contradiction": "Rubik",
  "difference and diversity": "Montserrat",
  "direct encounter": "Inter",
  "discovery and inquiry": "Nunito Sans",
  "discovery process": "Fredoka",
  "dissonance and harm": "Creepster",
  "dissonance and violence": "Nosifer",
  "dissonance violence": "Road Rage",
  "diversity and contradiction": "DM Sans",
  "doubt and challenge": "Exo 2",
  "duality contrast": "Bodoni Moda",
  "embodied experience": "Caveat",
  "embodied experience safety": "Nunito",
  "embodied expression movement": "Dancing Script",
  "embodied movement": "Pacifico",
  "embodied safety": "Quicksand",
  "embodied safety impulses": "Comfortaa",
  "embodied safety pleasure": "Fredoka",
  "embodied self": "Indie Flower",
  "embodied sensation": "Satisfy",
  "embodied sense making": "Lora",
  "embodied stillness": "Merriweather",
  "emotion empathy connection": "Great Vibes",
  "emotional connection": "Cookie",
  "emotional experience": "Kalam",
  "emotional experience states": "Caveat",
  "emotional performance feedback": "Exo 2",
  "emotional sensitivity": "Courgette",
  "emotional states": "Shadows Into Light",
  "emotional warmth peace": "Nunito",
  "engagement and frustration": "Creepster",
  "enjoyment and sensation": "Pacifico",
  "enjoyment sensation satisfaction": "DynaPuff",
  "environmental adaptation": "Roboto Flex",
  "epistemology and virtue": "EB Garamond",
  "experience and writing": "Lora",
  "experience writing encounter": "Merriweather",
  "experiential expression": "Caveat",
  "exploration and discovery": "Indie Flower",
  "exploration discovery": "Amatic SC",
  "exploratory discovery": "Gloria Hallelujah",
  "expression and belonging": "Dancing Script",
  "expression and communication": "Open Sans",
  "expression and connection": "Great Vibes",
  "expression and relationships": "Pacifico",
  "expression connection": "Cookie",
  "external presentation": "Playfair Display",
  "external reality": "Roboto",
  "external reality interface": "Inter",
  "external social reality": "Lato",
  "facades and forms": "Monoton",
  "fear and worry": "Creepster",
  "feedback and performance": "Space Grotesk",
  "flexibility and adaptation": "Roboto Flex",
  "flexibility and movement": "Dancing Script",
  "flexibility and transition": "Raleway",
  "flexibility openness transitions": "Nunito",
  "flexible life navigation": "Quicksand",
  "flexible movement": "Pacifico",
  "flux and growth": "Montserrat",
  "forms and facades": "Playfair Display",
  "forms facades surfaces": "Inter",
  "gratitude and possibility": "Great Vibes",
  "group conflict dynamics": "Barlow",
  "group dynamics": "Work Sans",
  "group dynamics conflict": "Archivo",
  "hedonic sensation": "Pacifico",
  "hope and cooperation": "Nunito",
  "human condition": "Merriweather",
  "human dignity": "EB Garamond",
  "human dignity futures": "Space Grotesk",
  "human flourishing": "Playfair Display",
  "human nature civility": "Lora",
  "human nature rights": "IBM Plex Serif",
  "human rights dignity": "Cinzel",
  "human rights values": "PT Serif",
  "human values": "Open Sans",
  "humanity consciousness rights": "Spectral",
  "identity expression": "Indie Flower",
  "image and play": "Caveat",
  "imagery and performance": "Lobster Two",
  "imagination and play": "Amatic SC",
  "imagination and roles": "Comic Neue",
  "imaginative engagement": "Dancing Script",
  "imaginative play": "Permanent Marker",
  "imagined roles": "Sacramento",
  "incompatible conditions": "Space Mono",
  "incompatible states": "Inconsolata",
  "incompleteness": "Fredericka the Great",
  "incompleteness necessity": "Special Elite",
  "individual neurotype": "Atkinson Hyperlegible Next",
  "individual neurotypes": "Lexend",
  "inquiry and discovery": "Figtree",
  "integration and change": "Poppins",
  "intellectual capacity": "IBM Plex Sans",
  "intellectual coherence": "Roboto",
  "intellectual functioning": "Source Sans 3",
  "intensity visibility presence": "Anton",
  "intentional creation": "Playfair Display",
  "interfaces and displays": "DM Sans",
  "internal struggle": "Fredericka the Great",
  "interpersonal understanding": "Noto Sans",
  "interpretation and identity": "Great Vibes",
  "interpretation and misunderstanding": "Caveat Brush",
  "interpretation identity": "Pacifico",
  "interpretation self-deception identity": "Lobster",
  "interpretive distortion": "Creepster",
  "interpretive illusion": "Monoton",
  "knowledge and animals": "Pacifico",
  "knowledge and identity": "Caudex",
  "purpose": "Roboto",
  "Phenomenology": "EB Garamond",
  "knowledge and trust": "Merriweather",
  "learning and collaboration": "Open Sans",
  "learning boundaries": "Roboto Condensed",
  "learning collaboration": "Nunito Sans",
  "learning collaboration boundaries": "Source Sans 3",
  "listening and resonance": "Lora",
  "lived experience": "Caveat",
  "lived experience writing": "Indie Flower",
  "logical justification": "IBM Plex Sans",
  "martial arts training": "Oswald",
  "mathematical optimization": "Space Mono",
  "meditative practice": "Raleway",
  "mental capacity": "Archivo",
  "mental distress": "Special Elite",
  "mental processing": "DM Sans",
  "metamorphic rest": "Metamorphous",
  "misinterpretation": "Creepster",
  "motivation and integrity": "Gravitas One",
  "motivation commitment values": "Playfair Display",
  "movement and flexibility": "Fredoka",
  "movement and structure": "Barlow",
  "movement and transition": "Work Sans",
  "movement flexibility": "Quicksand",
  "multiplicity and contradiction": "Exo 2",
  "multiplicity and scale": "Roboto Flex",
  "multiplicity difference": "Noto Sans",
  "natural change": "Poppins",
  "necessity and completion": "Anton",
  "necessity completion": "Bebas Neue",
  "neurodivergence": "Atkinson Hyperlegible Next",
  "neurodiversity": "Inclusive Sans",
  "neurodiversity identity": "Caveat",
  "neurodiversity spectrum": "Roboto Flex",
  "neurological difference": "Lexend",
  "neurological variation": "Readex Pro",
  "neurotype and identity": "Ubuntu",
  "neurotypical perspective": "Inter",
  "observation analysis perspective": "Spectral",
  "observation and analysis": "Noto Serif",
  "optimization constraints": "Space Mono",
  "optimization techniques": "IBM Plex Mono",
  "paradox and diversity": "Cormorant Garamond",
  "paradox and duality": "Abril Fatface",
  "paradox and plurality": "Mulish",
  "paradox diversity": "Eczar",
  "paradox diversity contrast": "Fraunces",
  "performance and emotion": "Dancing Script",
  "performance and feedback": "Roboto",
  "performance emotional feedback": "Merriweather",
  "performance feedback": "Inter",
  "performance metrics": "IBM Plex Sans",
  "performative identity": "Playfair Display",
  "personal agency": "Outfit",
  "personal agency values": "Roboto",
  "personal commitment": "Lora",
  "personal commitment drive": "Oswald",
  "personal commitment growth": "Nunito",
  "personal development": "Poppins",
  "personal motivation values": "DM Sans",
  "perspective and analysis": "Inter",
  "physical expression": "Caveat",
  "physical expression movement": "Permanent Marker",
  "physical movement": "Kalam",
  "physical separation": "Roboto Condensed",
  "physical stillness": "EB Garamond",
  "play and roles": "Pacifico",
  "play social roles": "Comic Neue",
  "pleasurable sensation": "Satisfy",
  "pleasure and satisfaction": "Great Vibes",
  "pleasure sensation": "Allura",
  "positive potential": "Fredoka",
  "possibility and gratitude": "Quicksand",
  "possibility gratitude energy": "Poppins",
  "potential and gratitude": "Nunito",
  "potential gratitude": "Raleway",
  "power dynamics": "Gravitas One",
  "practical success": "Roboto",
  "practical support": "Open Sans",
  "prediction and discovery": "Space Grotesk",
  "predictive adaptability discovery": "Roboto Flex",
  "presence and attention": "Merriweather",
  "presence and intensity": "Anton",
  "presence attention": "DM Sans",
  "presence intensity": "Oswald",
  "presence listening resonance": "Lora",
  "present listening": "Caveat",
  "present moment listening": "Kalam",
  "primate behavior": "Fredericka the Great",
  "primate comparison": "Creepster",
  "protective adaptation": "Roboto Slab",
  "psyche and healing": "Indie Flower",
  "psychological commitment": "PT Serif",
  "psychological coping": "Lora",
  "psychological coping mechanisms": "Merriweather",
  "psychological defense": "Rubik",
  "psychological development": "Poppins",
  "psychological engagement": "Inter",
  "psychological growth": "Merriweather",
  "psychological growth healing": "Lora",
  "psychological growth systems": "Inter",
  "psychological healing": "Open Sans",
  "psychological healing systems": "Roboto",
  "psychological structure": "IBM Plex Sans",
  "psychological structures": "Source Sans 3",
  "psychological systems": "Inter",
  "psychological systems healing": "PT Sans",
  "rational justification": "Roboto",
  "reason and justice": "IBM Plex Sans",
  "reason justice": "Source Sans 3",
  "receptive awareness": "Raleway",
  "receptive presence": "Quicksand",
  "reflective writing": "Lora",
  "regenerative pause": "Poppins",
  "regenerative renewal": "Raleway",
  "regenerative rest": "Quicksand",
  "relational conditions": "Open Sans",
  "relational encounter": "Fira Sans",
  "renewal and metamorphosis": "Dancing Script",
  "renewal transformation": "Great Vibes",
  "representation and play": "Pacifico",
  "resonant presence": "Montserrat",
  "resource support": "Nunito",
  "resources and success": "Roboto",
  "resources and support": "Lato",
  "rest and metamorphosis": "Playfair Display",
  "rest and renewal": "Raleway",
  "rest and transformation": "Libre Baskerville",
  "restorative transformation": "Merriweather",
  "rhythmic embodiment": "Caveat",
  "rhythmic physical expression": "Kalam",
  "self-actualization": "Playfair Display",
  "self-doubt": "Special Elite",
  "self-doubt and criticism": "Creepster",
  "self-doubt challenges": "Caveat",
  "sensory pleasure": "Satisfy",
  "sensory satisfaction": "Pacifico",
  "separation embodied stillness": "Spectral",
  "shared community": "Open Sans",
  "shared community experience": "Nunito Sans",
  "shared existence": "Lato",
  "shared expression": "Indie Flower",
  "shared human condition": "Merriweather",
  "simple answers": "Inter",
  "simultaneity and subjectivity": "Work Sans",
  "simultaneity subjectivity": "Mulish",
  "simultaneous subjective experience": "Raleway",
  "simultaneous subjectivity": "DM Sans",
  "situational constraints": "IBM Plex Sans",
  "social alienation": "Space Mono",
  "social belonging": "Nunito Sans",
  "social change activism": "Anton",
  "social change movement": "Bebas Neue",
  "social engagement friction": "Space Grotesk",
  "social engagement frustration": "Creepster",
  "social engagement struggles": "Special Elite",
  "social environment": "Open Sans",
  "social existence": "Lora",
  "social facades": "Playfair Display",
  "social friction": "Barlow",
  "social frustration": "Fredericka the Great",
  "social frustration oppression": "Archivo Black",
  "social orientation": "Roboto",
  "social presentation": "Montserrat",
  "social reality": "Inter",
  "social reality interface": "JetBrains Mono",
  "social structures": "Oswald",
  "social structures roles": "Archivo",
  "social suffering": "Bitter",
  "social transformation": "Rubik",
  "spatial interiority": "Poppins",
  "stillness and embodiment": "Merriweather",
  "stillness and physicality": "EB Garamond",
  "stillness and separation": "Cormorant Garamond",
  "structural analysis": "IBM Plex Mono",
  "structural appearance": "PT Sans",
  "structural compatibility": "Fira Sans",
  "subjective multiplicity": "Caveat",
  "substances and organisms": "Noto Sans",
  "support and success": "Ubuntu",
  "support success resources": "Nunito",
  "surface appearance": "Raleway",
  "surface appearances": "Quicksand",
  "surface forms": "Outfit",
  "surface presentation": "Prata",
  "survival and resilience": "Roboto Slab",
  "survival instinct": "Anton",
  "sustenance support": "Lato",
  "systemic incompatibility": "Oxanium",
  "systemic social change": "Space Grotesk",
  "systems and programming": "Space Mono",
  "systems and technology": "Courier Prime",
  "systems healing growth": "Poppins",
  "systems programming": "JetBrains Mono",
  "technical display": "Orbitron",
  "technological display": "Press Start 2P",
  "technological interface": "IBM Plex Mono",
  "technological interfaces": "IBM Plex Sans",
  "technology display": "Space Grotesk",
  "thinking and intelligence": "Roboto",
  "transformation and change": "Roboto Flex",
  "transformation and rest": "Raleway",
  "transformation and surprise": "Bungee Spice",
  "transformation change": "Exo 2",
  "transformation rest": "Lora",
  "transformation shapeshifting": "Orbitron",
  "transformative rest": "Poppins",
  "trust and knowledge": "Open Sans",
  "trust and thinking": "Inter",
  "trust knowledge": "Merriweather",
  "trust knowledge thinking": "Source Serif 4",
  "trust leadership": "Playfair Display",
  "uncertainty and adaptation": "Figtree",
  "understanding and integration": "Nunito",
  "violence and dissonance": "Creepster",
  "wisdom and skepticism": "EB Garamond",
  "wisdom and thought": "Noto Serif",
  "wisdom and trust": "PT Serif",
  "wisdom trust": "Crimson Text"
};

/**
 * Get font path for a keyword or cluster label
 * Returns path to .woff2 file in /public/fonts/google/
 */
export function getFontPath(keyword: string): string {
  const fontFamily = KEYWORD_FONTS[keyword];
  if (!fontFamily) {
    return "/fonts/source-code-pro-regular.woff2"; // fallback
  }

  // Convert font family to safe filename
  const safeFamily = fontFamily.replace(/\s+/g, "-").replace(/[^a-zA-Z0-9-]/g, "");
  return `/fonts/google/${safeFamily}.woff2`;
}
