-- Add 256-dimensional embedding column for efficient similarity computations
-- These are truncated + normalized versions of the full 1536-dim embeddings
-- (OpenAI's text-embedding-3-small supports Matryoshka truncation)

alter table keywords add column if not exists embedding_256 vector(256);

-- Index for fast similarity search on truncated embeddings
create index if not exists keywords_embedding_256_idx on keywords
  using ivfflat (embedding_256 vector_cosine_ops) with (lists = 100);

comment on column keywords.embedding_256 is
  'Truncated 256-dim embedding for efficient similarity computation. '
  'Generated by truncating first 256 dims of embedding and re-normalizing.';

-- Populate embedding_256 from existing embeddings (truncate + normalize)
-- This is idempotent - only updates rows where embedding_256 is NULL
update keywords
set embedding_256 = (
  select (array_agg(v / nullif(norm, 0) order by idx))::vector(256)
  from (
    select
      val as v,
      ordinality as idx,
      sqrt(sum(val * val) over ()) as norm
    from unnest((embedding::float[])[1:256]) with ordinality as t(val, ordinality)
  ) sub
)
where embedding is not null
  and embedding_256 is null;
